In [1]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("/kaggle/input/datasets/spscientist/students-performance-in-exams/StudentsPerformance.csv")

In [4]:
#Display Information
df.head(5)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [5]:
df.tail(5)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [9]:
df.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [11]:
df.isnull().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [17]:
mathAvg=int(df['math score'].mean())
readingAvg=int(df['reading score'].mean())
writingAvg=int(df['writing score'].mean())

print("Math Score average is: ",mathAvg)
print("Math Score average is: ",readingAvg)
print("Math Score average is: ",writingAvg)

Math Score average is:  66
Math Score average is:  69
Math Score average is:  68

In [25]:
#Making new Column
df['TotalMarks']= df['math score'] + df['reading score'] + df['writing score']

In [30]:
print(df.columns)

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score', 'TotalMarks', 'Average'],
      dtype='object')

In [28]:
top_5 = df.nlargest(5, 'TotalMarks')
print(top_5)

     gender race/ethnicity parental level of education     lunch  \
458  female        group E           bachelor's degree  standard
916    male        group E           bachelor's degree  standard
962  female        group E          associate's degree  standard
114  female        group E           bachelor's degree  standard
179  female        group D            some high school  standard

    test preparation course  math score  reading score  writing score  \
458                    none         100            100            100
916               completed         100            100            100
962                    none         100            100            100
114               completed          99            100            100
179               completed          97            100            100

     TotalMarks
458         300
916         300
962         300
114         299
179         297

In [29]:
#Making new Column
df['Average']= df['math score'].mean() + df['reading score'].mean() + df['writing score'].mean()

In [31]:
df[df['TotalMarks']<df['Average']]

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,TotalMarks,Average
3,male,group A,associate's degree,free/reduced,none,47,57,44,148,203.312
7,male,group B,some college,free/reduced,none,40,43,39,122,203.312
8,male,group D,high school,free/reduced,completed,64,64,67,195,203.312
9,female,group B,high school,free/reduced,none,38,60,50,148,203.312
10,male,group C,associate's degree,standard,none,58,54,52,164,203.312
...,...,...,...,...,...,...,...,...,...,...
986,female,group C,associate's degree,standard,none,40,59,51,150,203.312
988,female,group A,some high school,free/reduced,none,44,45,45,134,203.312
994,male,group A,high school,standard,none,63,63,62,188,203.312
996,male,group C,high school,free/reduced,none,62,55,55,172,203.312
997,female,group C,high school,free/reduced,completed,59,71,65,195,203.312

In [38]:
print("Total Number of Students: ",df.shape[0])

Total Number of Students:  1000

In [39]:
df.to_csv("ProcessedStudentPerformance.csv", index=False)